services:
  invoice:
    build: .
    container_name: invoice-app
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:[REDACTED]@host.docker.internal:5432/postgres
      NODE_ENV: production
    networks:
      - shared-network
    ports:
      - "3002:3000"

networks:
  shared-network:
    external: true
